# Playbook to initialize the ssh keys etc

- name: Delete mentions to the Hostnames of the cluster nodes in known_hosts
  ansible.builtin.known_hosts:
    name: "{{item}}"
    state: absent
  with_items: "{{groups['allnodes']}}"

- name: Add mentions to the Hostnames of the cluster nodes in known_hosts
  ansible.builtin.command: "ssh-keyscan -H {{item}}"
  register: key
  with_items: "{{groups['allnodes']}}"   

- name: Add mentions to the Hostnames of the cluster nodes in known_hosts
  ansible.builtin.known_hosts:
    name: "{{item.item}}"
    key: "{{item.stdout}}"
    state: present
  with_items: "{{key.results}}"     


# - name: Lookup IP addresses
#   debug:
#     msg: "{{ lookup('community.general.dig', '{{item}}')}}"
#   with_items: "{{groups['allnodes']}}"    

# - name: Delete mentions to the IP of the cluster nodes in known_hosts
#   ansible.builtin.known_hosts:
#     name: "{{ lookup('community.general.dig', '{{item}}')}}"
#     state: absent
#   with_items: "{{groups['allnodes']}}"  

# - name: Fetch keys for IPs/Hostnames of the cluster nodes in known_hosts
#   tags: "never,sshkeys"
#   ansible.builtin.command: "ssh-keyscan -H {{ip_addr}}"
#   register: key
#   ansible.builtin.known_hosts:
#     name: "{{item}}"
#     key: "{{key}}"
#     state: present
#   with_items: "{{groups['allnodes']}}"

# - debug:
#     var: "ip_addr"
#   with_items: "{{groups['allnodes']}}"    

# - debug:
#     var: ip_addr
#   with_items: "{{groups['allnodes']}}"     


