---
# This Playbook would deploy the whole hadoop cluster

# - hosts: admin  
#   gather_facts: yes
#   roles:
#   - role: init
  
# - hosts: allnodes
#   roles:
#   - role: bootstrap
#   - role: provision

- hosts: allnodes
  roles:
  - role: smoketest