---
# This Playbook would deploy the whole hadoop cluster

# - hosts: admin  
#   gather_facts: yes
#   roles:
#   - role: init
  
- hosts: allnodes
  roles:
  - role: bootstrap

# - hosts: namenodes
#   roles:
#   - role: namenode

# - hosts: datanodes
#   roles:
#   - role: workernode
