---
# This Playbook would deploy the whole hadoop cluster

- hosts: admin  
  gather_facts: yes
  roles:
  - role: init
    tags: [ never ]
  - role: config
    tags: [ config ]
  
- hosts: allnodes
  roles:
  - role: bootstrap
    tags: [ bootstrap ]
  - role: provision
    tags: [ provision ]

- hosts: namenodes
  tags: test
  roles:
  - role: smoketest