# Playbook that runs smoke test on the hadoop cluster

- name: Get smoke test components
  set_fact:
    smoketest_components_list: "{{smoketest_components | join(',')}}"

- debug:
    var: smoketest_components_list    

- name: Run smoke tests on the hadoop cluster components
  ansible.builtin.command: '/bigtop-home/provisioner/utils/smoke-tests.sh {{smoketest_components_list}}'
  become: True
  register: smoketest_out

- debug:
    var: smoketest_out.stdout_lines
- debug: 
    var: smoketest_out.stderr_lines

# - name: Calculate test location
#   set_fact:
#     test_loc: "/bigtop-home/bigtop-tests/smoke-tests/{{item}}/build/reports/tests/test/"
#   register: test_dir
#   with_items: "{{smoketest_components}}"

# - debug:
#     var: test_loc
# - debug:
#     var: test_dir    
# - name: Fetch smoketest results
#   ansible.builtin.fetch:
#     src: "{{item.ansible_facts.test_loc}}"
#     dest: "{{playbook_dir}}/smoke-tests/{{item.item}}"
#     flat: true
#   with_items: "{{test_dir.results}}"